# Generated by Django 4.1.9 on 2023-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthDetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mental_illness', models.CharField(default='N/A', max_length=255)),
            ],
        ),
    ]
