# Generated by Django 4.1.3 on 2023-06-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_post_evaluation_negative_post_evaluation_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redflag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
