# Generated by Django 4.1.3 on 2023-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_user_redflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messageAmountwithBot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
